# Generated by Django 2.1.4 on 2018-12-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Atuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa_Parceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('vagas_abertas', models.BooleanField(default=False)),
                ('area', models.ManyToManyField(to='nexo.Area_Atuacao')),
            ],
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True)),
                ('local', models.CharField(max_length=64, verbose_name='Local')),
                ('curso', models.ManyToManyField(to='nexo.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('email', models.CharField(max_length=64, verbose_name='E-mail')),
                ('linkedin', models.CharField(max_length=64, verbose_name='Likedin')),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Universitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, verbose_name='Email')),
                ('linkedin', models.CharField(max_length=64, verbose_name='Likedin')),
                ('telefone', models.CharField(max_length=64, verbose_name='Telefone')),
                ('comentario_hunter', models.TextField(blank=True, verbose_name='Comentário Hunter')),
                ('mes_graduacao', models.IntegerField(verbose_name='Mês graduação')),
                ('ano_graduacao', models.IntegerField(verbose_name='Ano graduação')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('salario_max', models.FloatField(verbose_name='Salário máximo')),
                ('salario_min', models.FloatField(verbose_name='Salário mínimo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexo.Empresa_Parceira')),
            ],
        ),
        migrations.CreateModel(
            name='Talento',
            fields=[
                ('universitario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nexo.Universitario')),
                ('nota_final', models.IntegerField()),
                ('comentario_hunter_final', models.TextField(blank=True, verbose_name='Comentário Hunter Final')),
                ('pretensao_salarial', models.FloatField(verbose_name='Pretensão Salarial')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexo.Vaga')),
            ],
            bases=('nexo.universitario',),
        ),
        migrations.AddField(
            model_name='universitario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexo.Curso'),
        ),
        migrations.AddField(
            model_name='universitario',
            name='faculdade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexo.Faculdade'),
        ),
        migrations.AddField(
            model_name='universitario',
            name='hunter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexo.Hunter'),
        ),
        migrations.AddField(
            model_name='universitario',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexo.Situacao'),
        ),
    ]
